### ISSUE TITLE
IE8 does not style adjacent sibling until redraw is forced

### ISSUE THREAD

**Issue by dotherightthing** [rdebeasi/checked-polyfill#2]
Hi,

My CSS does not work:

```
input[type="checkbox"].checked + label {
    /* some style */
}
```

The 'buggy sibling selector support in IE7' link in your docs is broken, is it similar to [Adjacent sibling selector not working with dynamically added class in IE7/8](http://stackoverflow.com/questions/11935581/adjacent-sibling-selector-not-working-with-dynamically-added-class-in-ie7-8)?

I have tried redefining my styles in this way, but they are still not being applied.

```
input[type="checkbox"] + label.checked {
    /* some style */
}
```

On that SO post, someone suggests toggling the class on a parent element to force a redraw - this works. Could you build that into the plugin somehow?

Thanks,
Dan

**Comment by pablinos** [comment]
I know this is a really old and closed issue but I just had a similar situation and it turns out that it was to do with having two comma separated rules. So:

```css
input.styled-checkbox + label.checked span {
    background:url(../images/checkbox-active.png) 0 0 no-repeat;
}

input.styled-checkbox:checked + label span {
    background:url(../images/checkbox-active.png) 0 0 no-repeat;
}
```

Works, where as:

```css
input.styled-checkbox:checked + label span,
input.styled-checkbox + label.checked span {
    background:url(../images/checkbox-active.png) 0 0 no-repeat;
}
```

Doesn't! Just thought it might be useful info for someone!
